Repository YoshithaRathnayake/NEW-YOSHITHA-WEBSITE, pull requests merged in 2022-10, with the labels that each got.

#72 Updated about section with new content
  dark/index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#78 Alignment of text and image
  dark/assets/css/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#91 Contact navbar link updated
  dark/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#77 Update the font type of About section
  dark/assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#97 Updated index.html
  dark/index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#109 :lipstick: feat: change about me font family and style
  dark/assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#112 Fix age from readme and index.html file
  README.md
  index.html
Labels: good first issue, hacktoberfest-accepted

#116 Update the age in meta tag descriptions
  .idea/.gitignore
  .idea/NEW-YOSHITHA-WEBSITE.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  index.html
  light/index.html
Labels: good first issue, hacktoberfest-accepted

#119 ```Clone your forked repository``` section and description are not stuck together now
  README.md
Labels: good first issue, hacktoberfest-accepted

#120 Add a sentence to contact section
  dark/index.html
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#125 Custom scrollbar
  assets/css/styles.css
  dark/assets/css/styles.css
  dark/index.html
  index.html
  light/assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#127 reduce scrollbar
  assets/css/styles.css
  dark/assets/css/styles.css
  light/assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#133 Use an and between the Bootstrap and Yaml in the readme.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#123 added email in contact section
  dark/assets/css/styles.css
  dark/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#136 Change the text color in the contact-section to white
  dark/assets/css/styles.css
  dark/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#137 Changed the color of the text in the contact us page to white
  dark/assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#141 Formatted All Code Files
  dark/assets/css/styles.css
  dark/index.html
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#142 Added contact form in contact section
  dark/assets/css/styles.css
  dark/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted
