Repository YoshithaRathnayake/NEW-YOSHITHA-WEBSITE, pull requests merged in 2022-12, with the labels that each got.

#152 Remove the unwanted email icon
  dark/index.html
Labels: good first issue

#157 Remove unwanted link tag from the contact section
  dark/index.html
Labels: good first issue

#156 Increase the gap between the email and the text in the contact text
  dark/index.html
Labels: good first issue

#169 Remove the background music code from index.html
  index.html
Labels: good first issue

#170 Remove the Elfsight app script tag from index.html
  index.html
Labels: good first issue

#172 Add the contact section heading background text
  dark/index.html
Labels: bug, good first issue

#171 Change the telegram icon in the social media icons
  dark/index.html
Labels: enhancement, good first issue

#174 Instagram icon was added in index.html
  dark/index.html
Labels: bug, good first issue

#185 About Me description is aligned to top little bit more
  dark/assets/css/styles.css
Labels: enhancement

#187 Reduce the font weight of the contact text
  dark/assets/css/styles.css
Labels: enhancement

#189 Change and edit the contact text
  dark/index.html
Labels: enhancement

#191 Remove unwanted codes in the css file
  dark/assets/css/styles.css
Labels: enhancement

#193 Reduce the border radius in the form in the contact section
  dark/index.html
Labels: enhancement

#195 Make the codes that got two lines for an element as a one line
  dark/index.html
  index.html
Labels: documentation, enhancement

#197 Update the code in the light theme
  light/index.html
Labels: documentation, enhancement

#199 Remove unwanted comments from index.html file
  dark/index.html
Labels: documentation, enhancement

#201 Add required comments to the index.html file
  dark/index.html
  index.html
Labels: documentation, enhancement

#203 Add missing tags to index.html files
  light/index.html
Labels: documentation, enhancement

#205 Remove unwanted directories
  .idea/.gitignore
  .idea/NEW-YOSHITHA-WEBSITE.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: documentation, enhancement
